FROM node:20

WORKDIR /app

# intall depenedcies
COPY package.json package-lock.json ./
RUN npm init -y && npm install express body-parser

# copy source code
COPY scripts/api.js /app/api.js

# start
CMD ["node", "api.js"]