FROM node:20

WORKDIR /app

# psql (for setup) and curl (for healthcheck)
RUN apt-get update && apt-get install -y postgresql-client curl bash && rm -rf /var/lib/apt/lists/*

# only copy files defining dependencies
COPY package.json package-lock.json ./
RUN npm ci

# copy the entire project (we need hardhat.config.ts as well)
COPY . .

# hardhat port
EXPOSE 8545

# start hardhat
CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]
