[Log]
Level = 'warn' # debug or info would slow down I/O

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[Database]
# Increase the number of database connections for parallel processing
MaxIdleConns = 20 # default is 10
MaxOpenConns = 200 # default is 100, need to add -c max_connections=200 for postgres ot work

[[EVM]]
ChainID = '31337'
Enabled = true
LinkContractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3'
MinIncomingConfirmations = 0  # default 3; don't wait for confirmations before a log event will be consumed
FinalityDepth = 1             # default 50

[[EVM.Nodes]]
Name = 'Hardhat'
HTTPURL = 'http://hardhat:8545'
WSURL = 'ws://hardhat:8545'

[EVM.Transactions]
# This is the most important for stress testing:
# How many transactions can be in the mempool at once (unconfirmed)
MaxInFlight = 2048 # default 16, 0 means disable
# How many transactions can wait in the DB for processing
MaxQueued = 4000 # default 250, 0 means disable
ResendAfterThreshold = '30s' # Default '1m', controls how long to wait before re-broadcasting a transaction that has not yet been confirmed.

[EVM.GasEstimator]
# For local testing, it's advisable to use a fixed price to save on estimateGas calls
Mode = 'FixedPrice' # default: 'BlockHistory'
PriceDefault = '1 gwei' # default '100 gwei', automatically set by ChainID, in case of hardhat its 1 gwei, so not required
PriceMin = '0'
PriceMax = '100 gwei'
BumpThreshold = 3 # default 3, this saves a few DB queries and calculations.
BumpPercent   = 20       # increase price by 20% per bump attempt
BumpMin       = '100 mwei' # minimum absolute bump — prevents no-op bumps

[EVM.NodePool]
PollInterval = '10s' # PollInterval controls how often to poll the node to check for liveness

[JobPipeline]
# keep the last 50 successful runs in the DB and UI
MaxSuccessfulRuns = 50 # default 10000
